@echo off
echo Iniciando Sistema de Activos...
echo --------------------------------
echo 1. Iniciando Queue Worker (Procesamiento en segundo plano)...
start "Laravel Queue Worker" php artisan queue:listen --timeout=0

echo 2. Iniciando Servidor Web...
php artisan serve
